### ISSUE TITLE
Example code not working for mesh.vertex_neighbor_vertices

### ISSUE THREAD

**Issue by DavidFernandezBonet** [eschnett/Delaunay.jl#2]
The following code do not compile for OS Windows 10 and Julia version 1.6

`using Delaunay`

`points = rand(10, 2)`

`mesh = delaunay(points)`

`mesh.points               `

`mesh.simplices                `

`mesh.neighbors             `

`mesh.vertex_to_simplex         `

`mesh.convex_hull           `
      
`mesh.vertex_neighbor_vertices `

The problem seems to be in the last line, and I think it has to do with the matrix dimensions of the input.

**Comment by denfc** [comment]
But they are being calculated (correctly?) because "Neighboring vertices of vertices:" are displayed when I set meshD equal to delaunay(points) on 10 randomly generated points in the REPL:

`
**julia> meshD= delaunay(points)**
Triangulation of 10 vertices in 2 dimensions
Coordinates of vertices:
    [0.6075222597963977 0.4835962368528399; 0.6704204089446105 0.03975485460582873; … ; 0.6182718173475975 0.8996977119853109; 0.1572020130369468 0.680570694650773]
Indices of simplices:
    [10 9 5; 9 10 6; … ; 1 7 4; 7 1 8]
Lookup array from vertices to some containing simplex:
    [10, 3, 3, 3, 1, 2, 8, 6, 1, 1]
Indices of facets of convex hull of the vertices:
    [9 5; 10 5; … ; 9 3; 10 2]
Indices of coplanar points, nearest facet, and nearest vertex:
    []
_**Neighboring vertices of vertices:**_
    [1]: [4, 6, 8, 7]
    [2]: [4, 3, 8, 10, 7]
    [3]: [4, 2, 9]
    [4]: [2, 3, 9, 6, 7, 1]
    [5]: [10, 9]
    [6]: [9, 10, 4, 8, 1]
    [7]: [4, 2, 8, 1]
    [8]: [10, 2, 6, 7, 1]
    [9]: [10, 5, 6, 4, 3]
    [10]: [9, 5, 6, 8, 2]

Error code is as follows:

`
**julia> meshD.vertex_neighbor_vertices**
10×10 SparseArrays.SparseMatrixCSC{Nothing, Int64} with 44 stored entries:
Error showing value of type SparseArrays.SparseMatrixCSC{Nothing, Int64}:
ERROR: MethodError: no method matching zero(::Type{Nothing})
Closest candidates are:
  zero(::Union{Type{P}, P}) where P<:Dates.Period at ~/julia-1.7.2/share/julia/stdlib/v1.7/Dates/src/periods.jl:53
  zero(::LinearAlgebra.UniformScaling{T}) where T at ~/julia-1.7.2/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:136
  zero(::AbstractIrrational) at ~/julia-1.7.2/share/julia/base/irrationals.jl:150

`
Is there another way to get to those points?  I'm new to the "Triangulation" type.

**Comment by eschnett** [comment]
When designing `Delaunay.jl`, I decided to represent graphs as sparse matrices. That's the right data structure, and is efficient, but unfortunately I also decided to save memory by using `Nothing` as element type for the `SparseArray`. This fails because `zero(::Type{Nothing})` is not defined.

I will change this to use `Bool` instead, and release a new version.

**Comment by eschnett** [comment]
See the new version 1.2.0.
